name: leetcode_dart
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

#dependencies:
#  collections: ^1.0.0

dev_dependencies:
  dart_code_metrics: ^4.17.1
  lints: ^2.0.0
  test: ^1.21.4
